#!/bin/bash


echo "Hello World"







'''Structure

#!/bin/bash                    #! is called shebang and it tells the system what interpreter that
                               that should be used to execute the file.
permissions                    File must be made executible.
			       chmod 755 - allows all users to execute the file
			       chmod 700 - only the owner to execute. 
command line syntax	       ./script_name
'''




