#! bin/bash
#: Description:         Using the built-in command test you can check the
#                       -e  existence of a file
#                       -f  type of a file.
#                       -d  a directory.
#                       -h or -L for symbolic link.
#                       -x execution of a file.
#
# Test-1:               Test whether a file exists using the -e flag.
#                       if the error-code $? == 0, which indicates success
#                       then we return the success message.  Note that we use
#                       [[ ]] to evaluate the expression.
#                       -eq is used to test the quality between two integers.
#
# Test-2:               Test whether a user defined file in the cwd exists.
#


###############################################################################
# Test-1 
###############################################################################
echo -e Test-1: Check if filename $file_name exists.

file_name=special_params
test -e $(pwd)/$file_name

if [[ $? -eq 0 ]]; then
    echo --- file-name exists.
else
    echo --- file-name not found.  Failed with error $?
fi
echo -e "\n"


###############################################################################
# Test-2 
###############################################################################
echo -e Test-2: Read file-name input from terminal and check if exists

# User Input
echo --- enter filename
read file_name

# Test if exists
test -e $(pwd)/$file_name

if [[ $? -eq 0 ]]; then
    echo --- file-name exists.
else
    echo --- file-name not found.  Failed with error $?
fi
echo -e "\n"











