#! bin/bash
#: Description:         Using the built-in command test you can check the
#
#: Options              -e  existence of a file
#                       -f  type of a file.
#                       -d  a directory.
#                       -h or -L for symbolic link.
#                       -x execution of a file.
#
# Test Operators        test -eq    test equality of intengers. Ex test 1 -eq 1
#                       test -ne    test inequality of integers.
#
###############################################################################
# Test 
###############################################################################
echo Test: simple integer comparison

if test 1 -eq 1; then
    echo --- 1 equals 1
else
    echo --- 1 not equal to 1
fi
echo -e "\n" # expansion of backslash to create new line
